### ISSUE TITLE
HA entities not updating despite regular API call

### ISSUE THREAD

**Issue by greyivy** [dahlb/ha_blueair#172]
Version: 1.17.8

My integration is not updating on Home Assistant. It looks like it's successfully calling the Blueair API regularly but not actually updating the sensor in HA. Entities update initially (on integration or HA restart) but never afterwards. My log (every 5 minutes or so):

```
2024-12-16 22:18:23.669 DEBUG (MainThread) [blueair_api.callbacks] Bedroom publishing updates
2024-12-16 22:18:23.669 DEBUG (MainThread) [blueair_api.device_aws] refreshed blueair device aws: DeviceAws(api=<blueair_api.http_aws_blueair.HttpAwsBlueair object at xxx>, uuid='xxx', name='Bedroom', name_api='xxx', mac='xxx', type_name='NB', sku='xxx', firmware='1.0.1', mcu_firmware='1.0.1', serial_number='xxx', brightness=0.0, child_lock=False, fan_speed=11.0, fan_auto_mode=True, standby=False, night_mode=False, germ_shield=NotImplemented, pm1=NotImplemented, pm2_5=0.0, pm10=NotImplemented, tVOC=NotImplemented, temperature=NotImplemented, humidity=NotImplemented, filter_usage_percentage=0.0, wifi_working=True, wick_usage_percentage=NotImplemented, wick_dry_mode=NotImplemented, water_shortage=NotImplemented, auto_regulated_humidity=NotImplemented)
2024-12-16 22:18:23.669 DEBUG (MainThread) [custom_components.ha_blueair.blueair_update_coordinator] Finished fetching ha_blueair-None data in 0.779 seconds (success: True)
```

**Comment by dahlb** [comment]
probably fixed in [1.17.9](https://github.com/dahlb/ha_blueair/commit/7ae0d937e2418e87dda327a88b54295ef8aa2817)

**Comment by greyivy** [comment]
Still not working, unfortunately. This is primarily for the PM2.5 sensor.

The changes in the graph are when I restarted Home Assistant.

![image](https://github.com/user-attachments/assets/180dcd60-ffc0-4a64-a713-47d62f89429d)

**Comment by MeeperBeeper** [comment]
I can confirm this.  I'm on 1.17.9 and sometime in the last two days or so all data points seem to be frozen.  I restart HA and it updates once but is then frozen again.  All sensors are like this.

The fan speed control also seems sticky like it's trying to show state one behind what it was just set to.

I'm on a Classic 480i if that helps.

**Comment by greyivy** [comment]
Deleted and added the integration, updated Home Assistant, tried with a new Blueair device and still getting the same result.

**Comment by rainwoodman** [comment]
might be related to https://github.com/dahlb/ha_blueair/blame/main/custom_components/ha_blueair/blueair_update_coordinator.py#L44? 

I noticed similar behavior on LED lights -- even when I force update by running the update-entity action from HA/developer tools, the entity state of the LED light entity did not update.

**Comment by dahlb** [comment]
I had time to verify this is fixed in 1.17.11.  either the ha core's update_coordinator isn't working as defined in https://developers.home-assistant.io/docs/integration_fetching_data/ or our use of dataclass isn't defining __eq__ like it is expected to, either way I think we can all agree consistency is more important then performance and I it do not have time to investigate either of those dependencies potential errors

**Comment by rainwoodman** [comment]
I read HA's source code. The root cause is that we mutate the self.blueair_api device object in-place then returns it as the data in the refresh() function.

Therefore the equality comparison between previous_data and self.data is always True, stopping update from ever happening.

In our datamodel, the device is both the state object and the API object. but in the HA documentation (fetching_data), self._device is the API object and the state is returned separately as an immutable, comparable object.
