### ISSUE TITLE
Blueair Sense+ Support in app

### ISSUE THREAD

**Issue by martindh73** [dahlb/ha_blueair#232]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_blueair/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Thanks for adding the Australia region to the app. Its all working in that it logs in but unfortunately it does not pick up my Sense+ air purifiers. Just wondering if they are supported.

### Describe the solution you'd like

Sense+ air purifier support in app.

### Describe alternatives you've considered

None

### Additional context

None

**Comment by martindh73** [comment]
Ok im not sure these are what you need to take a look but its what I was able to download as logs off the Blueair plugin.

[home-assistant_ha_blueair_2025-05-31T02-17-00.115Z.log](https://github.com/user-attachments/files/20530293/home-assistant_ha_blueair_2025-05-31T02-17-00.115Z.log)
[config_entry-ha_blueair-01JVKY8ST8PNKP8QPE3H2Z890T.json](https://github.com/user-attachments/files/20530294/config_entry-ha_blueair-01JVKY8ST8PNKP8QPE3H2Z890T.json)

**Comment by dahlb** [comment]
Thanks for your logs, I think v1.33.5 should fix this issue.

**Comment by martindh73** [comment]
Hi,

 

I’m still not picking up and devices or entities. Reran the logs with new version.

 

Cheers,

 

Martin

**Comment by dahlb** [comment]
I don't see any new logs, please attach them to the ticket at https://github.com/dahlb/ha_blueair/issues/232

**Comment by dahlb** [comment]
from your logs
```
2025-06-01 07:09:26.787 DEBUG (MainThread) [custom_components.ha_blueair] Legacy Login error: invalid password
```
blueair sense+ uses blueair's legacy api and in your logs the legacy api is failing to login with the error that you are using the wrong password.  My guess is you have blue air accounts in multiple regions with the same email but different passwords.  Are you using the same email/password in the integration that you use in the blueair mobile app?
